<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="models" nsURI="http://www.fever.org/models" nsPrefix="fever.models">
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spl" upperBound="-1" eType="#//SPL"
        eOpposite="#//SPL/variabilitymodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//VariabilityModelEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spl" eType="#//SPL" eOpposite="#//SPL/buildmodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MappedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbols" upperBound="-1"
        eType="#//MakeSymbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spl" eType="#//SPL" eOpposite="#//SPL/implementationmodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueFeatures" upperBound="-1"
        eType="#//ReferencedValueFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//FeatureConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" ordered="false"
        upperBound="-1" eType="#//ConditionalBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chane" eType="#//ChangeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variabilitymodel" eType="#//VariabilityModel"
        eOpposite="#//VariabilityModel/spl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildmodel" eType="#//BuildModel"
        eOpposite="#//BuildModel/spl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementationmodel" eType="#//ImplementationModel"
        eOpposite="#//ImplementationModel/spl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityModelEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//VariabilityTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prompt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValues" upperBound="-1"
        eType="#//DefaultValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selects" upperBound="-1"
        eType="#//Select"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PromptCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PresenceCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Depends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="External" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariabilityTypes">
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="TRISTATE"/>
    <eLiterals name="INT"/>
    <eLiterals name="HEX"/>
    <eLiterals name="STRING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//VariabilityModelEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//VariabilityModelEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//CompilationTarget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetType" eType="#//CompilationTargetType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedToSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompilationTargetType">
    <eLiterals name="COMPILATION_UNIT"/>
    <eLiterals name="FOLDER"/>
    <eLiterals name="CC_FLAG"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeSymbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//CompilationTarget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeType">
    <eLiterals name="ADDED"/>
    <eLiterals name="REMOVED"/>
    <eLiterals name="MODIFIED"/>
    <eLiterals name="MOVED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedValueFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueFeatures" upperBound="-1"
        eType="#//ReferencedValueFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="touched" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="FALSE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//ImplementationLine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editedBy" upperBound="-1"
        eType="#//CodeEdit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeEdit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rem_idx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="add_idx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rem_size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="add_size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
